# Generated by Django 3.1.3 on 2020-11-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Commande'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(max_length=5, null=True, verbose_name='Devise'),
        ),
    ]
